In [3]:
import numpy as np
import pandas as pd

### Creating a Data Frame

In [4]:
data = {
    "Name": ["John", "Anna", "Peter", "Linda"],
    "Age": [24,26,22,29],
    "City": ["Paris","Berlin","New York","London"],
    "Salary": [80000,75000,70000,90000]
}

df = pd.DataFrame(data)

In [7]:
df

    Name  Age      City  Salary
0   John   24     Paris   80000
1   Anna   26    Berlin   75000
2  Peter   22  New York   70000
3  Linda   29    London   90000

In [7]:
data = [
    ["John",24,"Paris",80000],
    ["Anna",26,"Berlin",75000],
    ["Peter",22,"New York",70000],
    ["Linda",29,"London",90000]
]
df2 = pd.DataFrame(data)

In [8]:
df2

       0   1         2      3
0   John  24     Paris  80000
1   Anna  26    Berlin  75000
2  Peter  22  New York  70000
3  Linda  29    London  90000

In [10]:
cols = ["Name","Age","City","Salary"]
new_df2 = pd.DataFrame(data,columns=cols,index=["a","b","c","d"])
new_df2

    Name  Age      City  Salary
a   John   24     Paris   80000
b   Anna   26    Berlin   75000
c  Peter   22  New York   70000
d  Linda   29    London   90000

### SELECTION AND INDEXING OF COLUMNS

In [38]:
new_df2["Name"]

a     John
b     Anna
c    Peter
d    Linda
Name: Name, dtype: str

In [39]:
new_df2[["Age","Salary"]]

   Age  Salary
a   24   80000
b   26   75000
c   22   70000
d   29   90000

### CREATING A NEW COLUMN

In [41]:
new_df2["Designation"] = ["Doctor","Engineer","Doctor","Engineer"]
new_df2

    Name  Age      City  Salary Designation
a   John   24     Paris   80000      Doctor
b   Anna   26    Berlin   75000    Engineer
c  Peter   22  New York   70000      Doctor
d  Linda   29    London   90000    Engineer

In [44]:
# it will only return the copy but would not update the exixting
new_df2.drop("Designation",axis=1)
new_df2

    Name  Age      City  Salary Designation
a   John   24     Paris   80000      Doctor
b   Anna   26    Berlin   75000    Engineer
c  Peter   22  New York   70000      Doctor
d  Linda   29    London   90000    Engineer

In [45]:
# In order to remove from the exixting we do inplace = True
new_df2.drop("Designation",axis=1, inplace=True)
new_df2

    Name  Age      City  Salary
a   John   24     Paris   80000
b   Anna   26    Berlin   75000
c  Peter   22  New York   70000
d  Linda   29    London   90000

In [49]:
# In order to remove 2 columns we do, we didn't do implace true as we do not want to completely remove salary age
new_df2.drop(["Salary","Age"],axis=1)

    Name      City
a   John     Paris
b   Anna    Berlin
c  Peter  New York
d  Linda    London

In [52]:
# Removing rows is kind of same as well
new_df2.drop(["a","d"],axis=0)

    Name  Age      City  Salary
b   Anna   26    Berlin   75000
c  Peter   22  New York   70000

### SELECTING A ROW

In [58]:
df2

       0   1         2      3
0   John  24     Paris  80000
1   Anna  26    Berlin  75000
2  Peter  22  New York  70000
3  Linda  29    London  90000

In [62]:
df2.loc[0]

0     John
1       24
2    Paris
3    80000
Name: 0, dtype: object

In [63]:
df2.loc[[1,2]]

       0   1         2      3
1   Anna  26    Berlin  75000
2  Peter  22  New York  70000

In [65]:
# Selecting with index
df2.iloc[[3,1]]

       0   1       2      3
3  Linda  29  London  90000
1   Anna  26  Berlin  75000

### SELECTING SUBSETS OF ROWS AND COLUMNS

In [66]:
df

       0   1         2      3
0   John  24     Paris  80000
1   Anna  26    Berlin  75000
2  Peter  22  New York  70000
3  Linda  29    London  90000

In [77]:
df.loc[[0,1]][[2,3]]

        2      3
0   Paris  80000
1  Berlin  75000

In [81]:
df.loc[[2,3]][[0,2]]

       0         2
2  Peter  New York
3  Linda    London

### CONDITIONAL SELECTION

In [84]:
new_df2

    Name  Age      City  Salary
a   John   24     Paris   80000
b   Anna   26    Berlin   75000
c  Peter   22  New York   70000
d  Linda   29    London   90000

In [85]:
# Select people with age greater than 25
new_df2[new_df2["Age"] > 25]

    Name  Age    City  Salary
b   Anna   26  Berlin   75000
d  Linda   29  London   90000

In [89]:
# Select people with age greater than 25 and city is London?  (tip: and is & in pandas)
new_df2[(new_df2["Age"] > 25) & (new_df2["City"] == "London")]

    Name  Age    City  Salary
d  Linda   29  London   90000

#### series  dataframe  missingdata  mergingjoinin  groupby  pivottable  operations  featureextraction  countries