In [1]:
import numpy as np 
import pandas as pd

### FINDING MISSING DATA

In [51]:
# In this whole file df is always the same no changes happen as we didnot write inplace = True
data = {
    "A": [1,2,np.nan,4,5],
    "B": [1,2,3,4,5],
    "C": [1,2,3,np.nan,np.nan],
    "D": [1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [19]:
# gives total nul values in each row
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [21]:
# checks if any null value exists in the columns
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

### REMOVING MISSING VALUES

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
# removing missing data always works on rows
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [35]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [40]:
# threshhold: it will return the rows which have atleast n non nul values
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

### FILLING THE MISSING DATA

In [41]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [54]:
df.fillna(10)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  10.0
2  10.0  3   3.0  10.0
3   4.0  4  10.0  10.0
4   5.0  5  10.0   5.0

In [53]:
# filling every column with diff values
values = {"A":10,"B":20,"C":30,"D":40}
df.fillna(value=values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  40.0
2  10.0  3   3.0  40.0
3   4.0  4  30.0  40.0
4   5.0  5  30.0   5.0

In [55]:
# filling mean data
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0