In [1]:
import numpy as np 
import pandas as pd

## NUMPY

In [10]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3,4], [5,6,7,8]])
tensor = np.array([[[1,2,3],[1,2,3]], [[5,6,7],[1,2,3]]])

print(tensor)
print(vector.size)
print(matrix.size)
print(matrix.shape)

[[[1 2 3]
  [1 2 3]]

 [[5 6 7]
  [1 2 3]]]
6
8
(2, 4)

In [17]:
zero = np.zeros((2,3))
print(zero)

ones = np.ones((4,5))
print(ones)

full = np.full((4,5),12)
print(full)

random = np.random.random((3,4))
print(random)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]
[[0.21887619 0.94510165 0.63614741 0.90056089]
 [0.5685487  0.60364    0.51453157 0.70963839]
 [0.70820878 0.03130225 0.59434856 0.23510387]]

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# print(arr[2:5])
# print(arr[-5:-1])
# print(arr[2:7:2])


arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr_2d[1:2])
print(arr_2d[:,1])
print(arr_2d[:,1:2])

[[4 5 6]]
[2 5 8]
[[2]
 [5]
 [8]]

In [35]:
unsorted_arr = np.array([4,6,1,2,9,7,3])
np.sort(unsorted_arr)

unsorted_2d_arr = np.array([[7,2],[4,9],[8,1]])
np.sort(unsorted_2d_arr)
np.sort(unsorted_2d_arr, axis=0)

array([[4, 1],
       [7, 2],
       [8, 9]])

In [39]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
print(numbers[numbers % 2 == 0])
print(numbers[numbers > 5])

np.where(numbers > 5)
np.where(numbers > 5, numbers*numbers, numbers)

[2 4 6 8]
[6 7 8 9]

array([ 1,  2,  3,  4,  5, 36, 49, 64, 81])

In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.concatenate((arr1,arr2))
arr1[2] = 5
print(arr1)

arr = np.array([[1,2,3,4], [5,6,7,8]])

arr[1][[1,2]] = 100
print(arr)

arr[1] = [10,20,30,40]
print(arr)

arr[:,0] = 10000
print(arr)

[1 2 5]
[[  1   2   3   4]
 [  5 100 100   8]]
[[ 1  2  3  4]
 [10 20 30 40]]
[[10000     2     3     4]
 [10000    20    30    40]]

In [53]:
original_arr = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
new_col = np.array([[7],[8]])

np.vstack((original_arr,new_row))
np.hstack((original_arr,new_col))

print(original_arr)
np.delete(original_arr)

[[1 2]
 [3 4]]

array([1, 3, 4])

In [66]:
# Data Structure: [restraunt_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], #restraunt 1
    [2, 120000, 140000, 160000, 190000], #restraunt 2
    [3, 200000, 230000, 260000, 300000], #restraunt 3
    [4, 180000, 210000, 240000, 270000], #restraunt 4
    [5, 160000, 185000, 205000, 230000]  #restraunt 5
])


np.sum(sales_data[:,1])

sum = np.sum(sales_data[:,3], axis=0)
print(sum)

summ = np.sum(sales_data[:,1:], axis=0)
print(summ)

1085000
[ 810000  945000 1085000 1240000]

In [75]:
vector1 = np.array([1,2,3,4])
vector2 = np.array([5,6,7,8])

a = np.add(vector1,vector2)
print(a)
b = np.sum((vector1,vector2))
print(b)

m = np.multiply(vector1,vector2)
print(m)
d = np.divide(vector1,vector2)
print(d)

[ 6  8 10 12]
36
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]

In [77]:
rest_types = np.array(["chinese", "indian", "burger", "pizza"])

a = np.vectorize(str.capitalize)
b = np.vectorize(str.upper)
print(a(rest_types))
print(b(rest_types))

['Chinese' 'Indian' 'Burger' 'Pizza']
['CHINESE' 'INDIAN' 'BURGER' 'PIZZA']

### PANDAS

In [99]:
data1 = {
    "Name": ["John", "Anna", "Peter", "Linda"],
    "Age": [24,26,22,29],
    "City": ["Paris","Berlin","New York","London"],
    "Salary": [80000,75000,70000,90000]
}

df = pd.DataFrame(data1)

In [100]:
data2 = [
    ["John",24,"Paris",80000],
    ["Anna",26,"Berlin",75000],
    ["Peter",22,"New York",70000],
    ["Linda",29,"London",90000]
]
df2 = pd.DataFrame(data2)

In [101]:
df

    Name  Age      City  Salary
0   John   24     Paris   80000
1   Anna   26    Berlin   75000
2  Peter   22  New York   70000
3  Linda   29    London   90000

In [102]:
df2

       0   1         2      3
0   John  24     Paris  80000
1   Anna  26    Berlin  75000
2  Peter  22  New York  70000
3  Linda  29    London  90000

In [104]:
cols = ["Name","Age","City","Salary"]
newDf2 = pd.DataFrame(data2,columns=cols)
newDf2

    Name  Age      City  Salary
0   John   24     Paris   80000
1   Anna   26    Berlin   75000
2  Peter   22  New York   70000
3  Linda   29    London   90000

In [105]:
newDf1 = pd.DataFrame(data1,index=[10,20,30,40])
newDf1

     Name  Age      City  Salary
10   John   24     Paris   80000
20   Anna   26    Berlin   75000
30  Peter   22  New York   70000
40  Linda   29    London   90000

In [107]:
df

    Name  Age      City  Salary
0   John   24     Paris   80000
1   Anna   26    Berlin   75000
2  Peter   22  New York   70000
3  Linda   29    London   90000

In [114]:
df[["Name","City"]]

In [115]:
df["designation"] = ["Doctor","Engineer","Doctor","Engineer"]

In [116]:
df

   Name  Age      City  Salary designation
0     1   24     Paris   80000      Doctor
1     2   26    Berlin   75000    Engineer
2    34   22  New York   70000      Doctor
3     4   29    London   90000    Engineer

In [121]:
df.drop("designation", axis=1, inplace=True)

In [122]:
df

   Name  Age      City  Salary
0     1   24     Paris   80000
1     2   26    Berlin   75000
2    34   22  New York   70000
3     4   29    London   90000

In [128]:
df.drop(["Name","Age"], axis=1)

       City  Salary
0     Paris   80000
1    Berlin   75000
2  New York   70000
3    London   90000

In [129]:
df

   Name  Age      City  Salary
0     1   24     Paris   80000
1     2   26    Berlin   75000
2    34   22  New York   70000
3     4   29    London   90000

In [130]:
df.drop([2,3],axis=0)

   Name  Age    City  Salary
0     1   24   Paris   80000
1     2   26  Berlin   75000

In [131]:
df

   Name  Age      City  Salary
0     1   24     Paris   80000
1     2   26    Berlin   75000
2    34   22  New York   70000
3     4   29    London   90000

In [137]:
df.loc[[1,3]]

   Name  Age    City  Salary
1     2   26  Berlin   75000
3     4   29  London   90000

In [140]:
df.iloc[[0,2]]

   Name  Age      City  Salary
0     1   24     Paris   80000
2    34   22  New York   70000

In [141]:
df

   Name  Age      City  Salary
0     1   24     Paris   80000
1     2   26    Berlin   75000
2    34   22  New York   70000
3     4   29    London   90000

In [146]:
df.loc[[0,1]][["City","Salary"]]

     City  Salary
0   Paris   80000
1  Berlin   75000

In [147]:
df

   Name  Age      City  Salary
0     1   24     Paris   80000
1     2   26    Berlin   75000
2    34   22  New York   70000
3     4   29    London   90000

In [148]:
df[(df["Age"] > 25)]

   Name  Age    City  Salary
1     2   26  Berlin   75000
3     4   29  London   90000

In [149]:
df[((df["Age"] > 25) & (df["Salary"] > 80000))]

   Name  Age    City  Salary
3     4   29  London   90000

In [150]:
data = {
    "A": [1,2,np.nan,4,5],
    "B": [1,2,3,4,5],
    "C": [1,2,3,np.nan,np.nan],
    "D": [1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [151]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [152]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [153]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [154]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [155]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [156]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [158]:
df.fillna(100)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  100.0
2  100.0  3    3.0  100.0
3    4.0  4  100.0  100.0
4    5.0  5  100.0    5.0

In [160]:
df.fillna(value={"A":100,"B":200,"C":300,"D":400},inplace=True)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0

In [161]:
df

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0

In [165]:
e = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
s = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [166]:
e

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [167]:
s

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [168]:
pd.merge(e,s)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [169]:
pd.merge(e,s,on="employee_id")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [171]:
pd.merge(e,s,on="employee_id",how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [172]:
pd.merge(e,s,on="employee_id",how="left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [173]:
pd.merge(e,s,on="employee_id",how="right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [174]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [175]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [176]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [179]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [180]:
pd.concat((df1,df2),axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [183]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [190]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [191]:
df2

   score
2     85
3     90
4     75

In [196]:
df1.join(df2,how="right")

      name  score
2      Bob     85
3  Charlie     90
4      NaN     75